title: ABM Foundation
description: Платформа для безопасного управления криптовалютными активами и инновационной технологией Abavault.
author: "ABM Team"
url: "https://abmfoundation.ru/"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
css: 
  - "style.css"
permalink: /:basename/
