theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">


css: style.css
